"""add trade_no field in Order

Revision ID: 71428352b9a6
Revises: 3293d1cf83fa
Create Date: 2019-02-15 10:07:04.989576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71428352b9a6'
down_revision = '3293d1cf83fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_order_info', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_order_info', 'trade_no')
    # ### end Alembic commands ###
